# Use a base image
FROM debian:bullseye

# Set environment variables
ENV JAVA_HOME=/usr/local/openjdk-11
ENV PATH=$JAVA_HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV LANG=C.UTF-8
ENV JAVA_VERSION=11.0.15
ENV CATALINA_HOME=/usr/local/tomcat
ENV TOMCAT_NATIVE_LIBDIR=$CATALINA_HOME/native-jni-lib
ENV LD_LIBRARY_PATH=$CATALINA_HOME/native-jni-lib
#ENV GPG_KEYS=48F8E69F6390C9F25CFEDCD268248959359E722B A9C5DF4D22E99998D9875A5110C01C5A2F6059E7 DCFD35E0BF8CA7344752DE8B6FB21E8933C60243
ENV TOMCAT_MAJOR=9
ENV TOMCAT_VERSION=9.0.62
#ENV TOMCAT_SHA512=179af1d50a7d330d0842d3f1cae086bbc1b20e8f6752d66500663f3ac71d80f50113bbd29931e21c8e2eccd982f9f872e193364311316fdd67349130d440c83f

# Install dependencies
RUN set -eux; \
    apt-get update && apt-get install -y --no-install-recommends \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Create the CATALINA_HOME directory
RUN mkdir -p "$CATALINA_HOME"

# Set the working directory
WORKDIR $CATALINA_HOME

# Copy server.xml and ROOT.war to the appropriate locations
COPY server.xml $CATALINA_HOME/conf/
COPY ROOT.war $CATALINA_HOME/webapps/

# Expose necessary ports
EXPOSE 8080
EXPOSE 8443

# Start Tomcat using catalina.sh
CMD ["catalina.sh", "run"]
