version: '3.9'
services:
  tim:
    container_name: TIM
    build:
      context: .
    ports:
      - 4859:8085
    networks:
      - tim

networks:
  tim:
    name: tim
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
