# Build stage
ARG tomcat_version=tomcat:9.0.62-jdk11-openjdk-slim
FROM openjdk:11-jdk as build

WORKDIR /workspace/app

ARG ID_LOG_VERSION=1.0.0-SNAPSHOT
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src
COPY libs libs

RUN ./mvnw install:install-file -Dfile=libs/id-log-${ID_LOG_VERSION}.jar -DgroupId=ee.ria.commons -DartifactId=id-log -Dversion=${ID_LOG_VERSION} -Dpackaging=jar -DgeneratePom=true

# Build the Spring Boot application
RUN ./mvnw package

# Tomcat installation stage
FROM $tomcat_version

# Copy the WAR file built in the previous stage to Tomcat's webapps directory
COPY --from=build /workspace/app/target/tim.war /usr/local/tomcat/webapps/ROOT.war

# Expose the default Tomcat ports
EXPOSE 8080
EXPOSE 8443

CMD ["catalina.sh", "run"]
